version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - web:web
      - api:api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/etc/logs/nginx
      - ./static:/var/www/mysite/public/
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api/src:/app/src"
    ports:
      - ${API_PORT}:8081
    depends_on:
      - mongo
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/app/src"
    ports:
      - ${WEB_PORT}:8082
    depends_on:
      - mongo
      - api
  mongo:
    command: mongod
    image: mongo
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./database/mongo:/data/db"
    logging:
      driver: "json-file"
